#!/usr/bin/env python3
"""
build.py — generate the furniture GLBs.

Runs two ways, because the repo is worked on from both:

    # with a local Blender install (any 4.2+ / 5.x)
    blender --background --python tools/blender/build.py -- --only sofa-3seat

    # with the headless Blender Python module (`pip install bpy`)
    python3 tools/blender/build.py --only sofa-3seat

Output goes to `public/models/` next to the CC0 assets, plus a manifest
(`tools/blender/manifest.json`) recording what each build actually produced:
triangle count, material count, measured footprint and file size. The manifest
is committed, and a unit test reads it — that is how the app's model registry
and these assets are kept from drifting apart.

Nothing here is wired into the app build. Assets are generated deliberately and
committed; a `npm run build` never needs Blender.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import asdict

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

from omega import pieces  # noqa: E402  (path setup must precede the import)
from omega.scene import BuiltAsset, finish, reset  # noqa: E402

DEFAULT_OUT = os.path.join(ROOT, "public", "models")
MANIFEST = os.path.join(HERE, "manifest.json")


def _argv() -> list[str]:
    """Blender passes script arguments after a bare `--`; plain Python does not."""
    if "--" in sys.argv:
        return sys.argv[sys.argv.index("--") + 1 :]
    # Under `blender --background --python x.py` with no `--`, argv is Blender's.
    return sys.argv[1:] if not sys.argv[0].endswith("blender") else []


def build_one(asset_id: str, out_dir: str) -> BuiltAsset:
    builder, nominal_cm = pieces.REGISTRY[asset_id]
    reset()
    builder()
    built = finish(asset_id, out_dir)

    # The catalog size is the contract with the app: a piece authored materially
    # larger or smaller than its footprint would be stretched into the wrong
    # proportions the moment the registry fits it. 4 cm of tolerance covers
    # bevels and overhanging handles.
    want_x, want_y = nominal_cm[0] / 100.0, nominal_cm[1] / 100.0
    if abs(built.size[0] - want_x) > 0.04 or abs(built.size[1] - want_y) > 0.04:
        print(
            f"  ! {asset_id}: footprint {built.size[0]:.2f}×{built.size[1]:.2f} m "
            f"differs from catalog {want_x:.2f}×{want_y:.2f} m",
            file=sys.stderr,
        )
    return built


def main() -> int:
    parser = argparse.ArgumentParser(description="Build OMEGA furniture GLBs with Blender.")
    parser.add_argument("--only", help="comma-separated asset ids (default: all)")
    parser.add_argument("--out", default=DEFAULT_OUT, help="output directory")
    parser.add_argument("--list", action="store_true", help="list known asset ids and exit")
    args = parser.parse_args(_argv())

    if args.list:
        for asset_id, (_, nominal) in sorted(pieces.REGISTRY.items()):
            print(f"{asset_id}\t{nominal[0]}×{nominal[1]} cm")
        return 0

    ids = (
        [i.strip() for i in args.only.split(",") if i.strip()]
        if args.only
        else sorted(pieces.REGISTRY)
    )
    unknown = [i for i in ids if i not in pieces.REGISTRY]
    if unknown:
        print(f"unknown asset ids: {', '.join(unknown)}", file=sys.stderr)
        return 2

    built: list[BuiltAsset] = []
    for asset_id in ids:
        try:
            asset = build_one(asset_id, args.out)
        except Exception as exc:  # one bad builder must not lose the rest
            print(f"  ✗ {asset_id}: {exc}", file=sys.stderr)
            continue
        built.append(asset)
        print(
            f"  ✓ {asset_id:16s} {asset.triangles:6d} tris  "
            f"{asset.materials} mat  {asset.bytes / 1024:6.1f} KB  "
            f"{asset.size[0]:.2f}×{asset.size[1]:.2f}×{asset.size[2]:.2f} m"
        )

    # Merge into the manifest so a partial build (`--only`) updates its own
    # entries and leaves the rest alone.
    manifest: dict[str, dict] = {}
    if os.path.exists(MANIFEST):
        with open(MANIFEST) as fh:
            manifest = json.load(fh).get("assets", {})
    for asset in built:
        record = asdict(asset)
        record["nominal"] = list(asset.nominal)
        record["size"] = [round(v, 4) for v in asset.size]
        manifest[asset.asset_id] = record

    with open(MANIFEST, "w") as fh:
        json.dump(
            {
                "note": "Generated by tools/blender/build.py — do not edit by hand.",
                "assets": dict(sorted(manifest.items())),
            },
            fh,
            indent=2,
        )
        fh.write("\n")

    total = sum(a.bytes for a in built)
    print(f"\n{len(built)}/{len(ids)} assets · {total / 1024:.0f} KB total → {args.out}")
    return 0 if len(built) == len(ids) else 1


if __name__ == "__main__":
    raise SystemExit(main())
