#!/usr/bin/env python3
"""
plants.py — generate the vegetation GLBs.

    blender --background --python tools/blender/plants.py -- --only tree-birch
    python3 tools/blender/plants.py

Output goes to `public/models/env/`, kept apart from the furniture because these
are not catalog items: they have no footprint to match and are placed by the
world generator, not by the user. Their manifest is `plants.json`.

The budget is the point. A neighbourhood plants hundreds of these and `Static`
merges them by material, so every triangle is paid for a few hundred times over.
`--max-tris` is enforced, not suggested.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import asdict

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

from omega import plants as lib  # noqa: E402
from omega.scene import finish, reset  # noqa: E402

DEFAULT_OUT = os.path.join(ROOT, "public", "models", "env")
MANIFEST = os.path.join(HERE, "plants.json")


def _argv() -> list[str]:
    if "--" in sys.argv:
        return sys.argv[sys.argv.index("--") + 1 :]
    return sys.argv[1:] if not sys.argv[0].endswith("blender") else []


def main() -> int:
    parser = argparse.ArgumentParser(description="Build OMEGA vegetation GLBs with Blender.")
    parser.add_argument("--only", help="comma-separated plant names")
    parser.add_argument("--out", default=DEFAULT_OUT)
    parser.add_argument("--max-tris", type=int, default=900)
    parser.add_argument("--list", action="store_true")
    args = parser.parse_args(_argv())

    if args.list:
        for name, (_, height) in sorted(lib.PLANTS.items()):
            print(f"{name}\t{height:.2f} m")
        return 0

    names = (
        [n.strip() for n in args.only.split(",") if n.strip()]
        if args.only
        else sorted(lib.PLANTS)
    )
    unknown = [n for n in names if n not in lib.PLANTS]
    if unknown:
        print(f"unknown plants: {', '.join(unknown)}", file=sys.stderr)
        return 2

    manifest: dict[str, dict] = {}
    if os.path.exists(MANIFEST):
        with open(MANIFEST) as fh:
            manifest = json.load(fh).get("plants", {})

    built = 0
    for name in names:
        builder, height = lib.PLANTS[name]
        try:
            reset()
            builder()
            asset = finish(name, args.out, max_triangles=args.max_tris)
        except Exception as exc:
            print(f"  ✗ {name}: {exc}", file=sys.stderr)
            continue

        # The authored height is the contract with the world generator: it
        # scales a plant by a factor, so the factor has to mean something.
        if abs(asset.size[2] - height) > 0.35:
            print(
                f"  ! {name}: {asset.size[2]:.2f} m tall, declared {height:.2f} m",
                file=sys.stderr,
            )

        record = asdict(asset)
        record["size"] = [round(v, 4) for v in asset.size]
        record["height"] = round(asset.size[2], 4)
        record["footprint"] = list(asset.nominal)
        manifest[name] = record
        built += 1
        print(
            f"  ✓ {name:16s} {asset.triangles:5d} tris  {asset.materials} mat  "
            f"{asset.bytes / 1024:6.1f} KB  {asset.size[2]:.2f} m"
        )

    # Drop records for plants that no longer exist. Merging alone let a removed
    # builder keep its manifest entry forever, and the app's conformance test
    # then looked for a file nothing builds any more.
    manifest = {k: v for k, v in manifest.items() if k in lib.PLANTS}

    with open(MANIFEST, "w") as fh:
        json.dump(
            {
                "note": "Generated by tools/blender/plants.py — do not edit by hand.",
                "plants": dict(sorted(manifest.items())),
            },
            fh,
            indent=2,
        )
        fh.write("\n")

    total = sum(m["bytes"] for m in manifest.values())
    print(f"\n{built}/{len(names)} plants · {total / 1024:.0f} KB → {args.out}")
    return 0 if built == len(names) else 1


if __name__ == "__main__":
    raise SystemExit(main())
