#!/usr/bin/env python3
"""
props.py — generate the street-furniture and vehicle GLBs.

    blender --background --python tools/blender/props.py -- --only bench
    python3 tools/blender/props.py

Output goes to `public/models/props/`, kept apart from both the catalog furniture
(`public/models/`) and the vegetation (`public/models/env/`) because each of the
three is owned by a different registry on the app side, and a shared directory
means a stale file in one of them silently satisfies another one's test. The
manifest is `props.json`.

The budget is the point, exactly as with the plants: a neighbourhood places
hundreds of lamps and bins, `Static` merges them by material, and a triangle here
is a triangle several hundred times over. `--max-tris` is enforced, not
suggested, and the declared size is checked against what was actually built — a
prop is placed at life size, so a drift is a lamp a head too tall or a car that
does not fit the bay it is parked in.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import asdict

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

from omega import props as lib  # noqa: E402
from omega.scene import finish, reset  # noqa: E402

DEFAULT_OUT = os.path.join(ROOT, "public", "models", "props")
MANIFEST = os.path.join(HERE, "props.json")


def _argv() -> list[str]:
    if "--" in sys.argv:
        return sys.argv[sys.argv.index("--") + 1 :]
    return sys.argv[1:] if not sys.argv[0].endswith("blender") else []


def main() -> int:
    parser = argparse.ArgumentParser(description="Build OMEGA street props GLBs with Blender.")
    parser.add_argument("--only", help="comma-separated prop names")
    parser.add_argument("--out", default=DEFAULT_OUT)
    parser.add_argument("--max-tris", type=int, default=1400)
    parser.add_argument("--list", action="store_true")
    args = parser.parse_args(_argv())

    if args.list:
        for name, (_, size) in sorted(lib.PROPS.items()):
            print(f"{name}\t{size[0]:.2f}×{size[1]:.2f}×{size[2]:.2f} m")
        return 0

    names = (
        [n.strip() for n in args.only.split(",") if n.strip()]
        if args.only
        else sorted(lib.PROPS)
    )
    unknown = [n for n in names if n not in lib.PROPS]
    if unknown:
        print(f"unknown props: {', '.join(unknown)}", file=sys.stderr)
        return 2

    manifest: dict[str, dict] = {}
    if os.path.exists(MANIFEST):
        with open(MANIFEST) as fh:
            manifest = json.load(fh).get("props", {})

    built = 0
    for name in names:
        builder, declared = lib.PROPS[name]
        try:
            reset()
            builder()
            asset = finish(name, args.out, max_triangles=args.max_tris)
        except Exception as exc:  # one bad builder must not lose the rest
            print(f"  ✗ {name}: {exc}", file=sys.stderr)
            continue

        for axis, (got, want) in enumerate(zip(asset.size, declared)):
            if abs(got - want) > 0.12:
                print(
                    f"  ! {name}: axis {'xyz'[axis]} is {got:.2f} m, declared {want:.2f} m",
                    file=sys.stderr,
                )

        record = asdict(asset)
        record["size"] = [round(v, 4) for v in asset.size]
        record["height"] = round(asset.size[2], 4)
        record["footprint"] = list(asset.nominal)
        manifest[name] = record
        built += 1
        print(
            f"  ✓ {name:16s} {asset.triangles:5d} tris  {asset.materials} mat  "
            f"{asset.bytes / 1024:6.1f} KB  "
            f"{asset.size[0]:.2f}×{asset.size[1]:.2f}×{asset.size[2]:.2f} m"
        )

    # Drop records for props that no longer exist. Merging alone let a removed
    # builder keep its manifest entry forever, and the app's conformance test
    # then looked for a file nothing builds any more.
    manifest = {k: v for k, v in manifest.items() if k in lib.PROPS}

    with open(MANIFEST, "w") as fh:
        json.dump(
            {
                "note": "Generated by tools/blender/props.py — do not edit by hand.",
                "props": dict(sorted(manifest.items())),
            },
            fh,
            indent=2,
        )
        fh.write("\n")

    total = sum(m["bytes"] for m in manifest.values())
    print(f"\n{built}/{len(names)} props · {total / 1024:.0f} KB → {args.out}")
    return 0 if built == len(names) else 1


if __name__ == "__main__":
    raise SystemExit(main())
