/**
 * GENERATED by `scripts/assets/build.mjs` — do not edit by hand.
 *
 * Real-world bounding size of each built model, in metres, as `[x, y, z]`.
 * The runtime fits a model to the footprint of the *instance* it is drawing, so
 * one asset serves every id and size that reuses it (the three plant ids, or a
 * piece the user resized) without a per-id scale factor in the registry.
 */

export const MODEL_SIZES: Record<string, readonly [number, number, number]> = {
  'armchair': [0.7484, 0.9331, 0.9000],
  'chair-dining': [0.3761, 0.8443, 0.5000],
  'nightstand': [0.4500, 0.4505, 0.3682],
  'plant': [0.5000, 0.7238, 0.4544],
  'table-coffee': [1.1000, 0.3569, 0.5492],
  'vase-floor': [0.3000, 0.5664, 0.3000],
}
